### ISSUE TITLE
It seems that some failures do not lead to unlock

### ISSUE THREAD

**Issue by Koncopd** [laminlabs/lndb#367]
I saw that in lndb accesss to lamin-site-assets failed, but it stayed locked. And then another test user from lamindb attempted to upload docs and got stuck.

I am not sure why this happens, it should be dealt with here https://github.com/laminlabs/lndb/blob/c2fff5439d4987b0d66d91134a17723f5293d0dd/lndb/__init__.py#L76

Need to investigate.

**Comment by Koncopd** [comment]
This maybe https://stackoverflow.com/questions/6234405/logging-uncaught-exceptions-in-python

**Comment by falexwolf** [comment]
Yes, I also observed that sometimes `lamin-site-assets` gets locked and then blocks another run. Your StackOverflow might be the explanation.
